[tool.pylint.main]

# Discover python modules and packages in the file system subtree.
recursive = true

[tool.pylint.basic]

# Naming style matching correct argument names.
argument-naming-style = "camelCase"
# Naming style matching correct attribute names.
attr-naming-style = "camelCase"
# Naming style matching correct constant names.
const-naming-style = "UPPER_CASE"
# Naming style matching correct function names.
function-naming-style = "camelCase"
# Naming style matching correct variable names.
variable-naming-style = "camelCase"

# Naming style matching correct class names.
class-naming-style = "PascalCase"
# Naming style matching correct class attribute names.
class-attribute-naming-style = "camelCase"
# Naming style matching correct class constant names.
class-const-naming-style = "UPPER_CASE"
# Naming style matching correct method names.
method-naming-style = "camelCase"

# Naming style matching correct module names.
module-naming-style = "snake_case"

[tool.pylint."messages control"]

# Disable the message, report, category or checker with the given id(s).
disable = [
  "missing-module-docstring",
  "missing-function-docstring",
  "missing-class-docstring",
  "redefined-builtin",
  "too-many-instance-attributes",
  "too-many-locals",
  "too-many-branches",
  "too-many-statements",
  "too-many-nested-blocks",
  "too-few-public-methods",
  "unnecessary-lambda-assignment"
]
